// GENERATED by assets/illustrations/gen_empty_states.py — do not edit by hand.
// Change the geometry there and run `pnpm gen:illustrations`; `pnpm check:illustrations`
// fails CI when this file and the generator disagree.

export type ArtTone = 'line' | 'paper' | 'soft' | 'accent' | 'accent-soft';

export interface ArtShape {
	el: 'rect' | 'circle' | 'path';
	tone: ArtTone;
	attrs: Record<string, string | number>;
}

export const ART_VIEWBOX = '0 0 160 120';

export type EmptyStateArt = 'invoices' | 'vendors' | 'payments' | 'inbox' | 'chart' | 'shield' | 'workflow' | 'documents';

export const EMPTY_STATE_ART: Record<EmptyStateArt, ArtShape[]> = {
	invoices: [
		{"el": "path", "tone": "soft", "attrs": {"d": "M26 104 C 26 97, 134 97, 134 104 C 134 111, 26 111, 26 104 Z"}},
		{"el": "rect", "tone": "paper", "attrs": {"x": 40, "y": 20, "width": 58, "height": 74, "rx": 6}},
		{"el": "rect", "tone": "paper", "attrs": {"x": 56, "y": 28, "width": 62, "height": 76, "rx": 6}},
		{"el": "path", "tone": "line", "attrs": {"d": "M66 44 H96"}},
		{"el": "path", "tone": "line", "attrs": {"d": "M66 52 H106"}},
		{"el": "path", "tone": "line", "attrs": {"d": "M66 60 H90"}},
		{"el": "path", "tone": "line", "attrs": {"d": "M66 72 H108"}},
		{"el": "path", "tone": "line", "attrs": {"d": "M92 84 H108"}},
		{"el": "circle", "tone": "accent-soft", "attrs": {"cx": 116, "cy": 90, "r": 13}},
		{"el": "circle", "tone": "accent", "attrs": {"cx": 116, "cy": 90, "r": 13}},
		{"el": "path", "tone": "accent", "attrs": {"d": "M110 90 L114.0 94.0 L122 86.0"}},
		{"el": "path", "tone": "accent", "attrs": {"d": "M34 30 V38 M30 34 H38"}},
	],
	vendors: [
		{"el": "path", "tone": "soft", "attrs": {"d": "M26 104 C 26 97, 134 97, 134 104 C 134 111, 26 111, 26 104 Z"}},
		{"el": "rect", "tone": "paper", "attrs": {"x": 44, "y": 50, "width": 72, "height": 52, "rx": 4}},
		{"el": "path", "tone": "paper", "attrs": {"d": "M38 50 L46 28 H114 L122 50 Z"}},
		{"el": "path", "tone": "line", "attrs": {"d": "M58 28 L54 50 M72 28 L70 50 M88 28 L90 50 M102 28 L106 50"}},
		{"el": "rect", "tone": "accent-soft", "attrs": {"x": 70, "y": 72, "width": 20, "height": 30, "rx": 3}},
		{"el": "path", "tone": "accent", "attrs": {"d": "M70 102 V75 a3 3 0 0 1 3 -3 H87 a3 3 0 0 1 3 3 V102"}},
		{"el": "rect", "tone": "line", "attrs": {"x": 52, "y": 62, "width": 12, "height": 10, "rx": 2}},
		{"el": "rect", "tone": "line", "attrs": {"x": 96, "y": 62, "width": 12, "height": 10, "rx": 2}},
		{"el": "path", "tone": "accent", "attrs": {"d": "M128 26 V34 M124 30 H132"}},
	],
	payments: [
		{"el": "path", "tone": "soft", "attrs": {"d": "M26 104 C 26 97, 134 97, 134 104 C 134 111, 26 111, 26 104 Z"}},
		{"el": "rect", "tone": "paper", "attrs": {"x": 28, "y": 34, "width": 76, "height": 50, "rx": 7}},
		{"el": "path", "tone": "line", "attrs": {"d": "M28 48 H104"}},
		{"el": "rect", "tone": "accent-soft", "attrs": {"x": 38, "y": 58, "width": 16, "height": 12, "rx": 2}},
		{"el": "rect", "tone": "accent", "attrs": {"x": 38, "y": 58, "width": 16, "height": 12, "rx": 2}},
		{"el": "path", "tone": "line", "attrs": {"d": "M62 66 H90"}},
		{"el": "path", "tone": "line", "attrs": {"d": "M62 74 H80"}},
		{"el": "circle", "tone": "paper", "attrs": {"cx": 116, "cy": 88, "r": 16}},
		{"el": "circle", "tone": "paper", "attrs": {"cx": 116, "cy": 80, "r": 16}},
		{"el": "circle", "tone": "accent-soft", "attrs": {"cx": 116, "cy": 80, "r": 9}},
		{"el": "circle", "tone": "accent", "attrs": {"cx": 116, "cy": 80, "r": 9}},
		{"el": "path", "tone": "accent", "attrs": {"d": "M128 38 V46 M124 42 H132"}},
	],
	inbox: [
		{"el": "path", "tone": "soft", "attrs": {"d": "M26 104 C 26 97, 134 97, 134 104 C 134 111, 26 111, 26 104 Z"}},
		{"el": "path", "tone": "paper", "attrs": {"d": "M34 66 L50 36 H110 L126 66 V96 a4 4 0 0 1 -4 4 H38 a4 4 0 0 1 -4 -4 Z"}},
		{"el": "path", "tone": "line", "attrs": {"d": "M34 66 H62 a4 4 0 0 1 4 4 v2 a6 6 0 0 0 6 6 H88 a6 6 0 0 0 6 -6 v-2 a4 4 0 0 1 4 -4 H126"}},
		{"el": "path", "tone": "accent", "attrs": {"d": "M80 16 V44 M70 34 L80 44 L90 34"}},
		{"el": "path", "tone": "accent", "attrs": {"d": "M30 26 V34 M26 30 H34"}},
		{"el": "path", "tone": "accent", "attrs": {"d": "M132 23 V29 M129 26 H135"}},
	],
	chart: [
		{"el": "path", "tone": "soft", "attrs": {"d": "M26 104 C 26 97, 134 97, 134 104 C 134 111, 26 111, 26 104 Z"}},
		{"el": "rect", "tone": "paper", "attrs": {"x": 30, "y": 22, "width": 100, "height": 78, "rx": 6}},
		{"el": "rect", "tone": "soft", "attrs": {"x": 44, "y": 70, "width": 12, "height": 20, "rx": 2}},
		{"el": "rect", "tone": "soft", "attrs": {"x": 62, "y": 58, "width": 12, "height": 32, "rx": 2}},
		{"el": "rect", "tone": "accent-soft", "attrs": {"x": 80, "y": 48, "width": 12, "height": 42, "rx": 2}},
		{"el": "rect", "tone": "soft", "attrs": {"x": 98, "y": 38, "width": 12, "height": 52, "rx": 2}},
		{"el": "path", "tone": "line", "attrs": {"d": "M44 90 H116"}},
		{"el": "path", "tone": "accent", "attrs": {"d": "M50 64 L68 52 L86 42 L104 32"}},
		{"el": "circle", "tone": "accent", "attrs": {"cx": 104, "cy": 32, "r": 3}},
		{"el": "path", "tone": "accent", "attrs": {"d": "M136 16 V24 M132 20 H140"}},
	],
	shield: [
		{"el": "path", "tone": "soft", "attrs": {"d": "M26 104 C 26 97, 134 97, 134 104 C 134 111, 26 111, 26 104 Z"}},
		{"el": "path", "tone": "paper", "attrs": {"d": "M80 16 L112 28 V56 C112 78, 98 92, 80 100 C62 92, 48 78, 48 56 V28 Z"}},
		{"el": "path", "tone": "accent-soft", "attrs": {"d": "M80 26 L103 35 V56 C103 72, 93 83, 80 90 C67 83, 57 72, 57 56 V35 Z"}},
		{"el": "path", "tone": "accent", "attrs": {"d": "M69 58 L76.3 65.3 L91 50.7"}},
		{"el": "path", "tone": "accent", "attrs": {"d": "M38 30 V38 M34 34 H42"}},
		{"el": "path", "tone": "accent", "attrs": {"d": "M124 73 V79 M121 76 H127"}},
	],
	workflow: [
		{"el": "path", "tone": "soft", "attrs": {"d": "M26 104 C 26 97, 134 97, 134 104 C 134 111, 26 111, 26 104 Z"}},
		{"el": "rect", "tone": "paper", "attrs": {"x": 22, "y": 30, "width": 36, "height": 24, "rx": 6}},
		{"el": "rect", "tone": "paper", "attrs": {"x": 102, "y": 30, "width": 36, "height": 24, "rx": 6}},
		{"el": "rect", "tone": "accent-soft", "attrs": {"x": 62, "y": 70, "width": 36, "height": 24, "rx": 6}},
		{"el": "rect", "tone": "accent", "attrs": {"x": 62, "y": 70, "width": 36, "height": 24, "rx": 6}},
		{"el": "path", "tone": "line", "attrs": {"d": "M58 42 C 70 42, 70 82, 62 82"}},
		{"el": "path", "tone": "line", "attrs": {"d": "M98 82 C 90 82, 90 42, 102 42"}},
		{"el": "path", "tone": "line", "attrs": {"d": "M30 42 H50"}},
		{"el": "path", "tone": "line", "attrs": {"d": "M110 42 H130"}},
		{"el": "path", "tone": "accent", "attrs": {"d": "M72 82 H88"}},
		{"el": "path", "tone": "accent", "attrs": {"d": "M80 18 V26 M76 22 H84"}},
	],
	documents: [
		{"el": "path", "tone": "soft", "attrs": {"d": "M26 104 C 26 97, 134 97, 134 104 C 134 111, 26 111, 26 104 Z"}},
		{"el": "rect", "tone": "paper", "attrs": {"x": 34, "y": 22, "width": 56, "height": 72, "rx": 6}},
		{"el": "path", "tone": "line", "attrs": {"d": "M44 38 H80"}},
		{"el": "path", "tone": "line", "attrs": {"d": "M44 46 H72"}},
		{"el": "path", "tone": "line", "attrs": {"d": "M44 54 H78"}},
		{"el": "path", "tone": "line", "attrs": {"d": "M44 62 H64"}},
		{"el": "circle", "tone": "accent-soft", "attrs": {"cx": 98, "cy": 70, "r": 18}},
		{"el": "circle", "tone": "accent", "attrs": {"cx": 98, "cy": 70, "r": 18}},
		{"el": "path", "tone": "accent", "attrs": {"d": "M111 83 L124 96"}},
		{"el": "path", "tone": "accent", "attrs": {"d": "M126 26 V34 M122 30 H130"}},
	],
};
